<?php
/**
 * @file
 *  Commerce Registration install file.
 *
 *  Modify the registration schema to accomodate a commerce order ID number.
 */

/**
 * Implements hook_schema_alter().
 */
function commerce_registration_schema_alter(&$schema) {
  $schema['registration']['fields']['order_id'] = array(
    'description' => 'The order associated with this registration, if any.',
    'type' => 'int',
    'not null' => TRUE,
    'default' => 0,
  );
}