<?php
/**
 * @file
 *   Commerce Registration module code.
 */

/**
 * Implements hook_menu().
 */
function commerce_registration_menu() {
  $menu = array();

  $menu['node/%node/registration'] = array(
    'title' => t('Registrations'),
    'access callback' => 'commerce_registration_registration_page_access',
    'access arguments' => array(1),
    'page callback' => 'commerce_registration_registration_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );

  return $menu;
}

function commerce_registration_registration_page_access($node) {
  return TRUE;
}

function commerce_registration_registration_page($node) {
  $prodids = array();
  foreach ($node->field_commerce_product[LANGUAGE_NONE] as $product) {
    $prodids[] = (int) $product['product_id'];
  }
  $header = array(t('Order'), t('Date'), t('Product'), t('Registrant'));
  $rows = array();
  foreach ($prodids as $product_id) {
    $reg = db_select('registration', 'r')->fields('r', array('registration_id', 'order_id', 'created', 'author_uid'));
    $reg->condition('r.entity_type', 'commerce_product')
      ->condition('r.eid', $product_id)
      ->condition('r.status', 1)
      ->condition('r.order_id', 0, '!=')
      ->orderBy('r.created', 'DESC');
    $reg = $reg->execute();
    foreach ($reg as $row) {
      $prod = commerce_product_load($product_id);
      $rows[] = array(
        l(t('Order #') . $row->order_id, 'user/' . $row->author_uid . '/orders/' . $row->order_id),
        date("F j, Y - g:i:s a", $row->created),
        $prod->title,
      );
    }
  }
  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Implements hook_commerce_checkout_page_info().
 */
function commerce_registration_commerce_checkout_page_info() {
  $pages = array();
  $pages['registration'] = array(
    'name' => t('Registration'),
    'title' => t('Registration Information'),
    'weight' => 5,
    'status_cart' => TRUE,
    'buttons' => TRUE,
  );
  return $pages;
}
/**
 * Implements hook_commerce_checkout_pane_info().
 */
function commerce_registration_commerce_checkout_pane_info() {
  $panes = array();
  $panes['registration_information'] = array(
    'title' => t('Registration Information'),
    'base' => 'commerce_registration_information',
    'page' => 'registration',
    'enabled' => TRUE,
    'weight' => -50,
    'review' => TRUE,
    'file' => 'includes/commerce_registration.checkout_pane.inc',
  );
  return $panes;
}